/**
 * AgentFlow Pro - Workflow Templates
 * Pre-built workflow templates for common use cases
 */

import { WorkflowTemplate } from '@/lib/workflow/types';

export const workflowTemplates: WorkflowTemplate[] = [
  // === TOURISM TEMPLATES (8) ===
  {
    id: 'tourism-1',
    name: 'Guest Welcome Automation',
    description: 'Automated welcome message when new booking is created',
    category: 'Tourism',
    icon: '👋',
    tags: ['tourism', 'messaging', 'automation'],
    usageCount: 0,
    workflow: {
      id: 'tourism-1',
      name: 'Guest Welcome Automation',
      description: 'Send automated welcome message for new bookings',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'New Booking', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'booking.created' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 200 }, data: { label: 'Generate Welcome', icon: '📝', type: 'agent', config: { agentId: 'communication-agent', input: 'Generate personalized welcome message', timeout: 30 } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 350 }, data: { label: 'Send Email', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'welcome-email' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 500 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Welcome sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'agent-1' },
        { id: 'conn-2', source: 'agent-1', target: 'action-1' },
        { id: 'conn-3', source: 'action-1', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'tourism-2',
    name: 'Check-in Reminder',
    description: 'Send check-in instructions 24 hours before arrival',
    category: 'Tourism',
    icon: '⏰',
    tags: ['tourism', 'messaging', 'reminder'],
    usageCount: 0,
    workflow: {
      id: 'tourism-2',
      name: 'Check-in Reminder',
      description: 'Automated check-in reminder 24h before arrival',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Schedule', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 */6 * * *' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Query Bookings', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'SELECT * FROM bookings WHERE checkin - now() < 24h' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Generate Instructions', icon: '💬', type: 'agent', config: { agentId: 'communication-agent', input: 'Generate check-in instructions', timeout: 30 } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Send SMS', icon: '📱', type: 'action', config: { actionType: 'notification', channel: 'sms' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Reminders sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'agent-1' },
        { id: 'conn-3', source: 'agent-1', target: 'action-2' },
        { id: 'conn-4', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'tourism-3',
    name: 'Review Response Automation',
    description: 'AI-powered responses to guest reviews',
    category: 'Tourism',
    icon: '⭐',
    tags: ['tourism', 'reviews', 'ai'],
    usageCount: 0,
    workflow: {
      id: 'tourism-3',
      name: 'Review Response Automation',
      description: 'Automatically respond to guest reviews with AI',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'New Review', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'review.created' } } },
        { id: 'condition-1', type: 'condition', position: { x: 400, y: 200 }, data: { label: 'Rating >= 4?', icon: '❓', type: 'condition', config: { expression: 'rating >= 4', operator: 'greater_than' } } },
        { id: 'agent-1', type: 'agent', position: { x: 200, y: 350 }, data: { label: 'Positive Response', icon: '😊', type: 'agent', config: { agentId: 'communication-agent', input: 'Generate thank you for positive review', timeout: 30 } } },
        { id: 'agent-2', type: 'agent', position: { x: 600, y: 350 }, data: { label: 'Recovery Response', icon: '😔', type: 'agent', config: { agentId: 'communication-agent', input: 'Generate recovery response for negative review', timeout: 30 } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Post Response', icon: '🌐', type: 'action', config: { actionType: 'api', endpoint: '/api/reviews/respond', method: 'POST' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Response posted' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'condition-1' },
        { id: 'conn-2', source: 'condition-1', target: 'agent-1', sourceHandle: 'true' },
        { id: 'conn-3', source: 'condition-1', target: 'agent-2', sourceHandle: 'false' },
        { id: 'conn-4', source: 'agent-1', target: 'action-1' },
        { id: 'conn-5', source: 'agent-2', target: 'action-1' },
        { id: 'conn-6', source: 'action-1', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'tourism-4',
    name: 'Dynamic Pricing Update',
    description: 'AI-powered pricing based on demand and competition',
    category: 'Tourism',
    icon: '💰',
    tags: ['tourism', 'pricing', 'ai'],
    usageCount: 0,
    workflow: {
      id: 'tourism-4',
      name: 'Dynamic Pricing Update',
      description: 'Automated dynamic pricing optimization',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Daily Schedule', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 2 * * *' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 200 }, data: { label: 'Analyze Competitors', icon: '🔍', type: 'agent', config: { agentId: 'research-agent', input: 'Research competitor prices', timeout: 60 } } },
        { id: 'agent-2', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Calculate Optimal Price', icon: '🤖', type: 'agent', config: { agentId: 'optimization-agent', input: 'Calculate optimal pricing', timeout: 30 } } },
        { id: 'condition-1', type: 'condition', position: { x: 400, y: 500 }, data: { label: 'Price Change > 10%?', icon: '❓', type: 'condition', config: { expression: 'priceChange > 0.1', operator: 'greater_than' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 650 }, data: { label: 'Update Prices', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'UPDATE prices SET...' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 800 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Prices updated' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'agent-1' },
        { id: 'conn-2', source: 'agent-1', target: 'agent-2' },
        { id: 'conn-3', source: 'agent-2', target: 'condition-1' },
        { id: 'conn-4', source: 'condition-1', target: 'action-1' },
        { id: 'conn-5', source: 'action-1', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'tourism-5',
    name: 'Booking.com Sync',
    description: 'Two-way synchronization with Booking.com',
    category: 'Tourism',
    icon: '🔄',
    tags: ['tourism', 'channel', 'sync'],
    usageCount: 0,
    workflow: {
      id: 'tourism-5',
      name: 'Booking.com Sync',
      description: 'Sync bookings and availability with Booking.com',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Hourly', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 * * * *' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Fetch Bookings', icon: '🌐', type: 'action', config: { actionType: 'api', endpoint: 'https://api.booking.com/pull', method: 'GET' } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 350 }, data: { label: 'Update Local DB', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'INSERT/UPDATE bookings...' } } },
        { id: 'action-3', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Push Availability', icon: '🌐', type: 'action', config: { actionType: 'api', endpoint: 'https://api.booking.com/push', method: 'POST' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Sync complete' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'action-2' },
        { id: 'conn-3', source: 'action-2', target: 'action-3' },
        { id: 'conn-4', source: 'action-3', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'tourism-6',
    name: 'Post-Stay Feedback',
    description: 'Automated feedback collection after checkout',
    category: 'Tourism',
    icon: '📝',
    tags: ['tourism', 'feedback', 'automation'],
    usageCount: 0,
    workflow: {
      id: 'tourism-6',
      name: 'Post-Stay Feedback',
      description: 'Collect guest feedback after checkout',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Checkout Today', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'booking.checked_out' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 200 }, data: { label: 'Generate Survey', icon: '📝', type: 'agent', config: { agentId: 'content-agent', input: 'Generate personalized feedback survey', timeout: 30 } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 350 }, data: { label: 'Send Survey', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'feedback-survey' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 500 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Survey sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'agent-1' },
        { id: 'conn-2', source: 'agent-1', target: 'action-1' },
        { id: 'conn-3', source: 'action-1', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'tourism-7',
    name: 'Upsell Opportunities',
    description: 'Identify and offer upsells to guests',
    category: 'Tourism',
    icon: '💎',
    tags: ['tourism', 'upsell', 'revenue'],
    usageCount: 0,
    workflow: {
      id: 'tourism-7',
      name: 'Upsell Opportunities',
      description: 'Automated upsell offers to guests',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: '7 Days Before', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 9 * * *' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Find Eligible', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'SELECT bookings WHERE checkin - now() = 7 days' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Generate Offer', icon: '💬', type: 'agent', config: { agentId: 'content-agent', input: 'Generate personalized upsell offer', timeout: 30 } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Send Offer', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'upsell-offer' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Offers sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'agent-1' },
        { id: 'conn-3', source: 'agent-1', target: 'action-2' },
        { id: 'conn-4', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'tourism-8',
    name: 'Channel Availability Update',
    description: 'Update availability across all channels',
    category: 'Tourism',
    icon: '📅',
    tags: ['tourism', 'channel', 'availability'],
    usageCount: 0,
    workflow: {
      id: 'tourism-8',
      name: 'Channel Availability Update',
      description: 'Sync availability to all booking channels',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Booking Changed', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'booking.updated' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Get Availability', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'SELECT availability...' } } },
        { id: 'action-2', type: 'action', position: { x: 200, y: 350 }, data: { label: 'Update Booking.com', icon: '🌐', type: 'action', config: { actionType: 'api', endpoint: 'booking.com/api' } } },
        { id: 'action-3', type: 'action', position: { x: 400, y: 350 }, data: { label: 'Update Airbnb', icon: '🌐', type: 'action', config: { actionType: 'api', endpoint: 'airbnb.com/api' } } },
        { id: 'action-4', type: 'action', position: { x: 600, y: 350 }, data: { label: 'Update Expedia', icon: '🌐', type: 'action', config: { actionType: 'api', endpoint: 'expedia.com/api' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 500 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'All channels updated' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'action-2' },
        { id: 'conn-3', source: 'action-1', target: 'action-3' },
        { id: 'conn-4', source: 'action-1', target: 'action-4' },
        { id: 'conn-5', source: 'action-2', target: 'end-1' },
        { id: 'conn-6', source: 'action-3', target: 'end-1' },
        { id: 'conn-7', source: 'action-4', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },

  // === CONTENT TEMPLATES (4) ===
  {
    id: 'content-1',
    name: 'SEO Blog Post Generator',
    description: 'Generate SEO-optimized blog posts automatically',
    category: 'Content',
    icon: '📝',
    tags: ['content', 'seo', 'ai'],
    usageCount: 0,
    workflow: {
      id: 'content-1',
      name: 'SEO Blog Post Generator',
      description: 'Automated SEO blog post creation',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Keyword Input', icon: '👆', type: 'trigger', config: { type: 'manual' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 200 }, data: { label: 'Keyword Research', icon: '🔍', type: 'agent', config: { agentId: 'research-agent', input: 'Research keywords', timeout: 60 } } },
        { id: 'agent-2', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Generate Outline', icon: '📝', type: 'agent', config: { agentId: 'content-agent', input: 'Create blog outline', timeout: 30 } } },
        { id: 'agent-3', type: 'agent', position: { x: 400, y: 500 }, data: { label: 'Write Content', icon: '✍️', type: 'agent', config: { agentId: 'content-agent', input: 'Write full blog post', timeout: 120 } } },
        { id: 'agent-4', type: 'agent', position: { x: 400, y: 650 }, data: { label: 'SEO Optimize', icon: '🎯', type: 'agent', config: { agentId: 'optimization-agent', input: 'Optimize for SEO', timeout: 30 } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 800 }, data: { label: 'Publish', icon: '✅', type: 'end', config: { output: 'Blog post published' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'agent-1' },
        { id: 'conn-2', source: 'agent-1', target: 'agent-2' },
        { id: 'conn-3', source: 'agent-2', target: 'agent-3' },
        { id: 'conn-4', source: 'agent-3', target: 'agent-4' },
        { id: 'conn-5', source: 'agent-4', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'content-2',
    name: 'Social Media Scheduler',
    description: 'Auto-generate and schedule social media posts',
    category: 'Content',
    icon: '📱',
    tags: ['content', 'social', 'automation'],
    usageCount: 0,
    workflow: {
      id: 'content-2',
      name: 'Social Media Scheduler',
      description: 'Automated social media content creation',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Daily', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 8 * * *' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 200 }, data: { label: 'Generate Content', icon: '📝', type: 'agent', config: { agentId: 'content-agent', input: 'Generate social media post', timeout: 30 } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 350 }, data: { label: 'Schedule Post', icon: '📱', type: 'action', config: { actionType: 'api', endpoint: '/api/social/schedule' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 500 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Post scheduled' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'agent-1' },
        { id: 'conn-2', source: 'agent-1', target: 'action-1' },
        { id: 'conn-3', source: 'action-1', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'content-3',
    name: 'Product Description Generator',
    description: 'Generate product descriptions at scale',
    category: 'Content',
    icon: '🏷️',
    tags: ['content', 'ecommerce', 'ai'],
    usageCount: 0,
    workflow: {
      id: 'content-3',
      name: 'Product Description Generator',
      description: 'Bulk product description generation',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Product List', icon: '👆', type: 'trigger', config: { type: 'manual' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Get Products', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'SELECT products...' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Generate Descriptions', icon: '✍️', type: 'agent', config: { agentId: 'content-agent', input: 'Write product descriptions', timeout: 60 } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Update Products', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'UPDATE products...' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Descriptions generated' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'agent-1' },
        { id: 'conn-3', source: 'agent-1', target: 'action-2' },
        { id: 'conn-4', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'content-4',
    name: 'Email Newsletter Creator',
    description: 'Create and send weekly newsletters',
    category: 'Content',
    icon: '📧',
    tags: ['content', 'email', 'automation'],
    usageCount: 0,
    workflow: {
      id: 'content-4',
      name: 'Email Newsletter Creator',
      description: 'Automated weekly newsletter creation',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Weekly', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 9 * * 1' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 200 }, data: { label: 'Gather Content', icon: '🔍', type: 'agent', config: { agentId: 'research-agent', input: 'Gather weekly highlights', timeout: 60 } } },
        { id: 'agent-2', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Write Newsletter', icon: '✍️', type: 'agent', config: { agentId: 'content-agent', input: 'Write newsletter', timeout: 60 } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Send Email', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'newsletter' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Newsletter sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'agent-1' },
        { id: 'conn-2', source: 'agent-1', target: 'agent-2' },
        { id: 'conn-3', source: 'agent-2', target: 'action-1' },
        { id: 'conn-4', source: 'action-1', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },

  // === AUTOMATION TEMPLATES (4) ===
  {
    id: 'automation-1',
    name: 'Lead Qualification',
    description: 'Automatically qualify and score incoming leads',
    category: 'Automation',
    icon: '🎯',
    tags: ['automation', 'sales', 'ai'],
    usageCount: 0,
    workflow: {
      id: 'automation-1',
      name: 'Lead Qualification',
      description: 'AI-powered lead scoring and qualification',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'New Lead', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'lead.created' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 200 }, data: { label: 'Score Lead', icon: '🤖', type: 'agent', config: { agentId: 'optimization-agent', input: 'Score lead quality', timeout: 30 } } },
        { id: 'condition-1', type: 'condition', position: { x: 400, y: 350 }, data: { label: 'Score > 70?', icon: '❓', type: 'condition', config: { expression: 'score > 70', operator: 'greater_than' } } },
        { id: 'action-1', type: 'action', position: { x: 200, y: 500 }, data: { label: 'Notify Sales', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'hot-lead' } } },
        { id: 'action-2', type: 'action', position: { x: 600, y: 500 }, data: { label: 'Add to Nurture', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'INSERT leads...' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Lead qualified' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'agent-1' },
        { id: 'conn-2', source: 'agent-1', target: 'condition-1' },
        { id: 'conn-3', source: 'condition-1', target: 'action-1', sourceHandle: 'true' },
        { id: 'conn-4', source: 'condition-1', target: 'action-2', sourceHandle: 'false' },
        { id: 'conn-5', source: 'action-1', target: 'end-1' },
        { id: 'conn-6', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'automation-2',
    name: 'Invoice Generation',
    description: 'Automatically generate and send invoices',
    category: 'Automation',
    icon: '📄',
    tags: ['automation', 'billing', 'finance'],
    usageCount: 0,
    workflow: {
      id: 'automation-2',
      name: 'Invoice Generation',
      description: 'Automated invoice creation and delivery',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Monthly', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 0 1 * *' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Get Customers', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'SELECT customers...' } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 350 }, data: { label: 'Generate PDF', icon: '📄', type: 'action', config: { actionType: 'file', templateId: 'invoice' } } },
        { id: 'action-3', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Send Invoice', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'invoice-email' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Invoices sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'action-2' },
        { id: 'conn-3', source: 'action-2', target: 'action-3' },
        { id: 'conn-4', source: 'action-3', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'automation-3',
    name: 'Data Backup',
    description: 'Automated daily database backup',
    category: 'Automation',
    icon: '💾',
    tags: ['automation', 'backup', 'database'],
    usageCount: 0,
    workflow: {
      id: 'automation-3',
      name: 'Data Backup',
      description: 'Automated daily database backup',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Daily 2AM', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 2 * * *' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Export Database', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'EXPORT DATABASE...' } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 350 }, data: { label: 'Upload to S3', icon: '☁️', type: 'action', config: { actionType: 'file', destination: 's3://backups' } } },
        { id: 'action-3', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Notify Success', icon: '📧', type: 'action', config: { actionType: 'notification', channel: 'email' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Backup complete' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'action-2' },
        { id: 'conn-3', source: 'action-2', target: 'action-3' },
        { id: 'conn-4', source: 'action-3', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'automation-4',
    name: 'Error Alert System',
    description: 'Monitor and alert on system errors',
    category: 'Automation',
    icon: '🚨',
    tags: ['automation', 'monitoring', 'alerts'],
    usageCount: 0,
    workflow: {
      id: 'automation-4',
      name: 'Error Alert System',
      description: 'Automated error monitoring and alerting',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Error Event', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'error occurred' } } },
        { id: 'condition-1', type: 'condition', position: { x: 400, y: 200 }, data: { label: 'Severity = Critical?', icon: '❓', type: 'condition', config: { expression: 'severity == critical', operator: 'equals' } } },
        { id: 'action-1', type: 'action', position: { x: 200, y: 350 }, data: { label: 'Page On-Call', icon: '📱', type: 'action', config: { actionType: 'notification', channel: 'sms', priority: 'urgent' } } },
        { id: 'action-2', type: 'action', position: { x: 600, y: 350 }, data: { label: 'Log Error', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'INSERT error_logs...' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 500 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Error handled' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'condition-1' },
        { id: 'conn-2', source: 'condition-1', target: 'action-1', sourceHandle: 'true' },
        { id: 'conn-3', source: 'condition-1', target: 'action-2', sourceHandle: 'false' },
        { id: 'conn-4', source: 'action-1', target: 'end-1' },
        { id: 'conn-5', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },

  // === E-COMMERCE TEMPLATES (4) ===
  {
    id: 'ecommerce-1',
    name: 'Abandoned Cart Recovery',
    description: 'Recover abandoned carts with automated emails',
    category: 'E-commerce',
    icon: '🛒',
    tags: ['ecommerce', 'cart', 'automation'],
    usageCount: 0,
    workflow: {
      id: 'ecommerce-1',
      name: 'Abandoned Cart Recovery',
      description: 'Automated abandoned cart recovery',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Cart Abandoned', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'cart.abandoned' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Wait 1 Hour', icon: '⏰', type: 'action', config: { actionType: 'file', delay: '1h' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Generate Email', icon: '✍️', type: 'agent', config: { agentId: 'content-agent', input: 'Write cart recovery email', timeout: 30 } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Send Email', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'cart-recovery' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Recovery email sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'agent-1' },
        { id: 'conn-3', source: 'agent-1', target: 'action-2' },
        { id: 'conn-4', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'ecommerce-2',
    name: 'Order Fulfillment',
    description: 'Automate order fulfillment workflow',
    category: 'E-commerce',
    icon: '📦',
    tags: ['ecommerce', 'fulfillment', 'automation'],
    usageCount: 0,
    workflow: {
      id: 'ecommerce-2',
      name: 'Order Fulfillment',
      description: 'Automated order fulfillment process',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'New Order', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'order.created' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Check Inventory', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'SELECT inventory...' } } },
        { id: 'condition-1', type: 'condition', position: { x: 400, y: 350 }, data: { label: 'In Stock?', icon: '❓', type: 'condition', config: { expression: 'stock > 0', operator: 'greater_than' } } },
        { id: 'action-2', type: 'action', position: { x: 200, y: 500 }, data: { label: 'Create Shipment', icon: '📦', type: 'action', config: { actionType: 'api', endpoint: '/api/shipping/create' } } },
        { id: 'action-3', type: 'action', position: { x: 600, y: 500 }, data: { label: 'Notify Backorder', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'backorder' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Order processed' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'condition-1' },
        { id: 'conn-3', source: 'condition-1', target: 'action-2', sourceHandle: 'true' },
        { id: 'conn-4', source: 'condition-1', target: 'action-3', sourceHandle: 'false' },
        { id: 'conn-5', source: 'action-2', target: 'end-1' },
        { id: 'conn-6', source: 'action-3', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'ecommerce-3',
    name: 'Product Review Request',
    description: 'Request reviews after product delivery',
    category: 'E-commerce',
    icon: '⭐',
    tags: ['ecommerce', 'reviews', 'automation'],
    usageCount: 0,
    workflow: {
      id: 'ecommerce-3',
      name: 'Product Review Request',
      description: 'Automated product review requests',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Delivered', icon: '📢', type: 'trigger', config: { type: 'event', eventType: 'order.delivered' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Wait 7 Days', icon: '⏰', type: 'action', config: { actionType: 'file', delay: '7d' } } },
        { id: 'agent-1', type: 'agent', position: { x: 400, y: 350 }, data: { label: 'Generate Request', icon: '✍️', type: 'agent', config: { agentId: 'content-agent', input: 'Write review request', timeout: 30 } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Send Email', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'review-request' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Review request sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'agent-1' },
        { id: 'conn-3', source: 'agent-1', target: 'action-2' },
        { id: 'conn-4', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'ecommerce-4',
    name: 'Low Stock Alert',
    description: 'Alert when product stock is low',
    category: 'E-commerce',
    icon: '⚠️',
    tags: ['ecommerce', 'inventory', 'alerts'],
    usageCount: 0,
    workflow: {
      id: 'ecommerce-4',
      name: 'Low Stock Alert',
      description: 'Automated low stock notifications',
      nodes: [
        { id: 'trigger-1', type: 'trigger', position: { x: 400, y: 50 }, data: { label: 'Hourly', icon: '⏰', type: 'trigger', config: { type: 'schedule', schedule: '0 * * * *' } } },
        { id: 'action-1', type: 'action', position: { x: 400, y: 200 }, data: { label: 'Check Stock', icon: '🗄️', type: 'action', config: { actionType: 'database', query: 'SELECT products WHERE stock < 10' } } },
        { id: 'condition-1', type: 'condition', position: { x: 400, y: 350 }, data: { label: 'Low Stock?', icon: '❓', type: 'condition', config: { expression: 'stock < 10', operator: 'less_than' } } },
        { id: 'action-2', type: 'action', position: { x: 400, y: 500 }, data: { label: 'Notify Manager', icon: '📧', type: 'action', config: { actionType: 'email', templateId: 'low-stock' } } },
        { id: 'end-1', type: 'end', position: { x: 400, y: 650 }, data: { label: 'Complete', icon: '✅', type: 'end', config: { output: 'Alert sent' } } },
      ],
      connections: [
        { id: 'conn-1', source: 'trigger-1', target: 'action-1' },
        { id: 'conn-2', source: 'action-1', target: 'condition-1' },
        { id: 'conn-3', source: 'condition-1', target: 'action-2' },
        { id: 'conn-4', source: 'action-2', target: 'end-1' },
      ],
      status: 'active',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  },
];

export function getTemplatesByCategory(category: string): WorkflowTemplate[] {
  return workflowTemplates.filter(t => t.category === category);
}

export function getTemplateById(id: string): WorkflowTemplate | undefined {
  return workflowTemplates.find(t => t.id === id);
}

export function searchTemplates(query: string): WorkflowTemplate[] {
  const lowerQuery = query.toLowerCase();
  return workflowTemplates.filter(
    t =>
      t.name.toLowerCase().includes(lowerQuery) ||
      t.description.toLowerCase().includes(lowerQuery) ||
      t.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}
