// AgentFlow Pro - page.tsx
// Generated by integrate-hero-section.ps1

import HeroSection from '@/components/HeroSection';

export default function HomePage() {
  return (
    <main>
      <HeroSection />
    </main>
  );
}
