/**
 * AgentFlow Pro - Code generation pipeline
 * LLM-powered when OPENAI_API_KEY set, else template fallback
 */

import { generateText } from "ai";
import { createOpenAI } from "@ai-sdk/openai";
import { getLlmApiKey } from "@/config/env";

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GenerateCodeResult {
  files: GeneratedFile[];
}

export interface CodeGeneratorContext {
  readme?: string;
  files?: Array<{ path: string; content: string }>;
}

function parseLlmResponse(text: string): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const blockRegex = /```(\S+)?\s*\n([\s\S]*?)```/g;
  let m: RegExpExecArray | null;
  while ((m = blockRegex.exec(text)) !== null) {
    const maybePath = m[1] ?? "";
    const content = m[2].trim();
    const path =
      maybePath && !maybePath.startsWith("ts") && !maybePath.startsWith("js")
        ? maybePath
        : `generated/file-${files.length + 1}.ts`;
    files.push({ path, content });
  }
  if (files.length > 0) return files;

  const lines = text.split("\n");
  let currentPath = "generated/output.ts";
  let currentContent: string[] = [];
  for (const line of lines) {
    if (line.startsWith("// path:") || line.startsWith("# path:")) {
      if (currentContent.length > 0) {
        files.push({ path: currentPath, content: currentContent.join("\n") });
      }
      currentPath = line.replace(/^#?\s*path:\s*/, "").trim() || currentPath;
      currentContent = [];
    } else {
      currentContent.push(line);
    }
  }
  if (currentContent.length > 0) {
    files.push({ path: currentPath, content: currentContent.join("\n") });
  }
  return files;
}

function templateFallback(
  task: string,
  context?: CodeGeneratorContext
): GenerateCodeResult {
  const fileCount = context?.files?.length ?? 0;
  const ctxSummary =
    fileCount > 0
      ? `Context: ${fileCount} file(s) referenced.`
      : context?.readme
        ? `Context: ${context.readme.slice(0, 300)}...`
        : "No repo context available.";

  const sanitizedTask = task.trim() || "implement feature";
  const timestamp = new Date().toISOString().slice(0, 10);

  return {
    files: [
      {
        path: `generated/${sanitizedTask.replace(/\s+/g, "-").slice(0, 30)}.ts`,
        content: `/**
 * Generated by AgentFlow Pro Code Agent
 * Task: ${sanitizedTask}
 * Date: ${timestamp}
 *
 * ${ctxSummary}
 */

// Placeholder - implement based on task
export function placeholder() {
  return "${sanitizedTask}";
}
`,
      },
    ],
  };
}

export async function generateCode(
  task: string,
  context?: CodeGeneratorContext,
  llmOverride?: { apiKey: string; baseURL?: string; model: string }
): Promise<GenerateCodeResult> {
  const llm = llmOverride ?? getLlmApiKey();
  if (!llm.apiKey || !task.trim()) {
    return templateFallback(task, context);
  }

  const ctxSummary =
    context?.files && context.files.length > 0
      ? context.files
        .map((f) => `--- ${f.path} ---\n${f.content.slice(0, 500)}`)
        .join("\n\n")
      : context?.readme
        ? context.readme.slice(0, 500)
        : "No additional context.";

  const prompt = `Generate TypeScript/JavaScript code for: ${task}

Context:
${ctxSummary}

Return each file as a markdown code block with the path in the first line or as \`\`\`path/to/file.ts
content
\`\`\`
Use TypeScript. Keep it concise and production-ready.`;

  try {
    const openai = createOpenAI({
      apiKey: llm.apiKey,
      ...(llm.baseURL && { baseURL: llm.baseURL }),
    });
    const { text } = await generateText({
      model: openai(llm.model),
      prompt,
    });
    const parsed = parseLlmResponse(text);
    if (parsed.length > 0) return { files: parsed };
  } catch {
    // Fall through to template
  }
  return templateFallback(task, context);
}
