/**
 * AgentFlow Pro - Code Agent
 * GitHub integration, code generation, review, PR auto-creation
 */

import type { Agent } from "../../orchestrator/Orchestrator";
import { getRepo, createBranch, createOrUpdateFile, createPullRequest } from "./github";
import { generateCode } from "./code-generator";
import { reviewCode } from "./code-review";

export interface CodeInput {
  task?: string;
  owner?: string;
  repo?: string;
  createPr?: boolean;
  context?: { readme?: string; files?: Array<{ path: string; content: string }> };
}

export interface CodeOutput {
  files?: Array<{ path: string; content: string }>;
  suggestions?: Array<{ path: string; line?: number; message: string; severity: string }>;
  pullRequest?: { url: string; number: number };
}

function captureSentry(err: unknown): void {
  if (!process.env.SENTRY_DSN) return;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const Sentry = require("@sentry/node");
    if (Sentry?.captureException) Sentry.captureException(err);
  } catch {
    // Sentry not installed or init failed
  }
}

export function createCodeAgent(config?: {
  githubToken?: string;
}): Agent {
  const token = config?.githubToken ?? process.env.GITHUB_TOKEN ?? "";

  return {
    id: "code-agent",
    type: "code",
    name: "Code Agent",
    execute: async (input: unknown): Promise<CodeOutput> => {
      const { task = "", owner, repo, createPr = false, context } = (input as CodeInput) ?? {};
      const output: CodeOutput = {};

      try {
        const generated = generateCode(task, context);
        output.files = generated.files;
        const review = reviewCode(generated.files);
        output.suggestions = review.suggestions;

        if (createPr && token && owner && repo && generated.files.length > 0) {
          const { defaultBranch, defaultBranchSha } = await getRepo(owner, repo, token);
          const branchName = `agentflow/code-${Date.now()}`;
          await createBranch(owner, repo, branchName, defaultBranchSha, token);

          for (const f of generated.files) {
            await createOrUpdateFile(
              owner,
              repo,
              f.path,
              f.content,
              `feat: ${task.slice(0, 50)}`,
              token,
              branchName
            );
          }

          const pr = await createPullRequest(
            owner,
            repo,
            branchName,
            defaultBranch,
            `Code Agent: ${task.slice(0, 80)}`,
            `Generated by AgentFlow Pro Code Agent.\n\nTask: ${task}\n\nSuggestions: ${review.suggestions.length}`,
            token
          );
          output.pullRequest = pr;
        }
      } catch (err) {
        captureSentry(err);
        throw err;
      }

      return output;
    },
  };
}
