/**
 * AgentFlow Pro - Code Agent
 * GitHub integration, code generation, review, PR auto-creation
 */

import type { Agent } from "../../orchestrator/Orchestrator";
import { mockMode } from "@/lib/mock-mode";
import {
  getFileContents,
  getDefaultBranchSha,
  pushFiles,
  createPullRequest,
} from "./github-client";
import { generateCode } from "./code-generator";
import { reviewCode } from "./code-reviewer";

export interface CodeInput {
  task?: string;
  owner?: string;
  repo?: string;
  createPr?: boolean;
  contextFilePath?: string;
  context?: { readme?: string; files?: Array<{ path: string; content: string }> };
}

export interface CodeOutput {
  files?: Array<{ path: string; content: string }>;
  suggestions?: Array<{ path: string; line?: number; message: string; severity: string }>;
  pullRequest?: { url: string; number: number };
}

function captureSentry(err: unknown): void {
  if (!process.env.SENTRY_DSN) return;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const Sentry = require("@sentry/node");
    if (Sentry?.captureException) Sentry.captureException(err);
  } catch {
    // Sentry not installed or init failed
  }
}

export function createCodeAgent(config?: {
  githubToken?: string;
  openaiKey?: string;
}): Agent {
  const token = config?.githubToken ?? process.env.GITHUB_TOKEN ?? "";
  const openaiKey = config?.openaiKey ?? process.env.OPENAI_API_KEY ?? "";

  return {
    id: "code-agent",
    type: "code",
    name: "Code Agent",
    execute: async (input: unknown): Promise<CodeOutput> => {
      const { task = "", owner, repo, createPr = false, contextFilePath, context } = (input as CodeInput) ?? {};
      const output: CodeOutput = {};

      if (mockMode) {
        return {
          files: [
            { path: "generated/mock-output.ts", content: `// Mock: ${task || "placeholder"}\nexport function mock() { return "dev"; }` },
          ],
          suggestions: [{ path: "generated/mock-output.ts", message: "Mock suggestion", severity: "info" }],
          pullRequest: createPr ? { url: "https://github.com/mock/pr", number: 1 } : undefined,
        };
      }

      let enrichedContext = { ...context };

      if (token && owner && repo && contextFilePath) {
        try {
          const fileContent = await getFileContents(owner, repo, contextFilePath, token);
          enrichedContext = { ...enrichedContext, readme: enrichedContext?.readme ?? fileContent };
        } catch {
          /* ignore */
        }
      }

      try {
        const generated = await generateCode(task, enrichedContext, openaiKey);
        output.files = generated.files;
        const review = reviewCode(generated.files);
        output.suggestions = review.suggestions;

        if (createPr && token && owner && repo && generated.files.length > 0) {
          const { defaultBranch } = await getDefaultBranchSha(owner, repo, token);
          const branchName = `agentflow/code-${Date.now()}`;
          await pushFiles(
            owner,
            repo,
            branchName,
            generated.files,
            `feat: ${task.slice(0, 50)}`,
            token
          );
          const pr = await createPullRequest(
            owner,
            repo,
            branchName,
            defaultBranch,
            `Code Agent: ${task.slice(0, 80)}`,
            `Generated by AgentFlow Pro Code Agent.\n\nTask: ${task}\n\nSuggestions: ${review.suggestions.length}`,
            token
          );
          output.pullRequest = pr;
        }
      } catch (err) {
        captureSentry(err);
        throw err;
      }

      return output;
    },
  };
}
