/**
 * AgentFlow Pro - Content generation pipeline
 * Template-based (placeholder for LLM integration)
 */

import type { Snippet } from "./context7";

export interface GeneratedContent {
  blog: string;
  social: string;
  email: string;
}

export function generateContent(
  topic: string,
  docsContext: Snippet[]
): GeneratedContent {
  const docsSummary =
    docsContext.length > 0
      ? docsContext.map((s) => `${s.title}: ${s.content.slice(0, 200)}...`).join("\n")
      : "No documentation context available.";

  return {
    blog: `# ${topic}\n\n${docsSummary}\n\n---\n*Generated by AgentFlow Pro Content Agent. Add LLM for full generation.*`,
    social: `${topic} - Key insights from docs. ${docsContext.length} reference(s). #agentflow #ai`,
    email: `Subject: ${topic}\n\nHi,\n\nHere's your content summary:\n\n${docsSummary}\n\nBest,\nAgentFlow Pro`,
  };
}
