/**
 * AgentFlow Pro - Content generation pipeline
 * Template-based (placeholder for LLM integration)
 */

import type { Snippet } from "./context7";

export interface GeneratedContent {
  blog: string;
  social: string;
  email: string;
}

export interface CompanyKnowledgeInput {
  products?: string[];
  competitors?: string[];
  keyFacts?: string[];
}

import type { GeoAeoHints } from "./seo-optimizer";

export interface GenerateContentOptions {
  brandVoiceSummary?: string | null;
  styleGuide?: string | null;
  visualGuidelines?: string | null;
  audienceContext?: string | null;
  companyKnowledge?: CompanyKnowledgeInput | null;
  geoHints?: GeoAeoHints | null;
  aeoHints?: GeoAeoHints | null;
}

export function generateContent(
  topic: string,
  docsContext: Snippet[],
  options?: GenerateContentOptions
): GeneratedContent {
  const docsSummary =
    docsContext.length > 0
      ? docsContext.map((s) => `${s.title}: ${s.content.slice(0, 200)}...`).join("\n")
      : "No documentation context available.";

  const parts: string[] = [docsSummary];

  const { brandVoiceSummary, styleGuide, visualGuidelines, audienceContext, companyKnowledge, geoHints, aeoHints } = options ?? {};
  if (brandVoiceSummary?.trim()) {
    parts.push(`[Brand Voice Context]\n${brandVoiceSummary.trim()}`);
  }
  if (styleGuide?.trim()) {
    parts.push(`[Style Guide]\n${styleGuide.trim()}`);
  }
  if (visualGuidelines?.trim()) {
    parts.push(`[Visual Guidelines]\n${visualGuidelines.trim()}`);
  }
  if (audienceContext?.trim()) {
    parts.push(`[Audience]\n${audienceContext.trim()}`);
  }
  if (companyKnowledge?.products?.length || companyKnowledge?.competitors?.length || companyKnowledge?.keyFacts?.length) {
    const ck: string[] = [];
    if (companyKnowledge.products?.length) ck.push(`Products: ${companyKnowledge.products.join(", ")}`);
    if (companyKnowledge.competitors?.length) ck.push(`Competitors: ${companyKnowledge.competitors.join(", ")}`);
    if (companyKnowledge.keyFacts?.length) ck.push(`Key facts: ${companyKnowledge.keyFacts.join(", ")}`);
    if (ck.length) parts.push(`[Company Knowledge]\n${ck.join("\n")}`);
  }
  if (geoHints?.faqSuggestions?.length || geoHints?.featuredSnippetHints?.length || geoHints?.conversionPatterns?.length) {
    const geo: string[] = [];
    if (geoHints.faqSuggestions?.length) geo.push(`FAQ ideas: ${geoHints.faqSuggestions.join(" | ")}`);
    if (geoHints.featuredSnippetHints?.length) geo.push(`Featured snippet tips: ${geoHints.featuredSnippetHints.join(" | ")}`);
    if (geoHints.conversionPatterns?.length) geo.push(`Conversion patterns: ${geoHints.conversionPatterns.join("; ")}`);
    if (geo.length) parts.push(`[GEO - Generative Engine Optimization]\n${geo.join("\n")}`);
  }
  if (aeoHints?.faqSuggestions?.length || aeoHints?.featuredSnippetHints?.length || aeoHints?.conversionPatterns?.length) {
    const aeo: string[] = [];
    if (aeoHints.faqSuggestions?.length) aeo.push(`AEO FAQ ideas: ${aeoHints.faqSuggestions.join(" | ")}`);
    if (aeoHints.featuredSnippetHints?.length) aeo.push(`AEO snippet tips: ${aeoHints.featuredSnippetHints.join(" | ")}`);
    if (aeoHints.conversionPatterns?.length) aeo.push(`AEO patterns: ${aeoHints.conversionPatterns.join("; ")}`);
    if (aeo.length) parts.push(`[AEO - Answer Engine Optimization]\n${aeo.join("\n")}`);
  }

  const contextBlock = parts.join("\n\n");

  return {
    blog: `# ${topic}\n\n${contextBlock}\n\n---\n*Generated by AgentFlow Pro Content Agent. Add LLM for full generation.*`,
    social: `${topic} - Key insights from docs. ${docsContext.length} reference(s). #agentflow #ai`,
    email: `Subject: ${topic}\n\nHi,\n\nHere's your content summary:\n\n${docsSummary}\n\nBest,\nAgentFlow Pro`,
  };
}
