/**
 * Guest Profile Manager Component
 * Comprehensive guest profile management with AI-powered recommendations
 */

"use client";

import { useState, useEffect } from 'react';
import { logger } from '@/infrastructure/observability/logger';
import { useGuestExperience } from '@/hooks/use-guest-experience';
import {
  GuestProfile,
  GuestPreferences,
  LoyaltyInfo,
  PersonalizedRecommendation,
  GuestTag,
  LoyaltyTier,
  CommunicationHistory,
  StayHistory,
  GuestFeedback,
} from '@/types/guest-experience';
import { format, subDays } from 'date-fns';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';

interface GuestProfileManagerProps {
  guestId: string;
  onProfileUpdate?: (profile: GuestProfile) => void;
}

export default function GuestProfileManager({ guestId, onProfileUpdate }: GuestProfileManagerProps) {
  const [activeTab, setActiveTab] = useState<'profile' | 'preferences' | 'loyalty' | 'recommendations' | 'history' | 'feedback'>('profile');
  const [editingSection, setEditingSection] = useState<string | null>(null);
  const [showRecommendationModal, setShowRecommendationModal] = useState(false);
  const [selectedRecommendation, setSelectedRecommendation] = useState<PersonalizedRecommendation | null>(null);

  const {
    profile,
    preferences,
    loyaltyInfo,
    recommendations,
    communicationHistory,
    stayHistory,
    feedback,
    tags,
    insights,
    isLoading,
    error,
    updateProfile,
    updatePreferences,
    addLoyaltyPoints,
    generateRecommendations,
    sendCommunication,
    recordFeedback,
    addTag,
    removeTag,
    getInsights,
    formatLoyaltyPoints,
    getLoyaltyTierColor,
    getLoyaltyTierBenefits,
    calculateStayValue,
    getGuestLifetimeValue,
  } = useGuestExperience({ guestId });

  useEffect(() => {
    if (profile && onProfileUpdate) {
      onProfileUpdate(profile);
    }
  }, [profile, onProfileUpdate]);

  const handleProfileUpdate = async (updates: Partial<GuestProfile>) => {
    try {
      await updateProfile(updates);
      setEditingSection(null);
    } catch (error) {
      logger.error('Failed to update profile:', error);
    }
  };

  const handlePreferencesUpdate = async (updates: Partial<GuestPreferences>) => {
    try {
      await updatePreferences(updates);
      setEditingSection(null);
    } catch (error) {
      logger.error('Failed to update preferences:', error);
    }
  };

  const handleAddPoints = async (points: number, reason: string) => {
    try {
      await addLoyaltyPoints(points, reason);
    } catch (error) {
      logger.error('Failed to add points:', error);
    }
  };

  const handleGenerateRecommendations = async () => {
    try {
      await generateRecommendations();
    } catch (error) {
      logger.error('Failed to generate recommendations:', error);
    }
  };

  const handleRecommendationAction = async (recommendation: PersonalizedRecommendation) => {
    setSelectedRecommendation(recommendation);
    setShowRecommendationModal(true);
  };

  const handleAddTag = async (tagName: string, category: string) => {
    try {
      await addTag({
        name: tagName,
        category: category as any,
        color: '#3b82f6',
        description: `Tag for ${tagName}`,
        autoGenerated: false,
        confidence: 1.0,
      });
    } catch (error) {
      logger.error('Failed to add tag:', error);
    }
  };

  const handleRemoveTag = async (tagId: string) => {
    try {
      await removeTag(tagId);
    } catch (error) {
      logger.error('Failed to remove tag:', error);
    }
  };

  const renderProfileTab = () => {
    if (!profile) return null;

    return (
      <div className="space-y-6">
        {/* Personal Information */}
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Personal Information</h3>
            <button
              onClick={() => setEditingSection(editingSection === 'personal' ? null : 'personal')}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              {editingSection === 'personal' ? 'Cancel' : 'Edit'}
            </button>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">First Name</label>
              <input
                type="text"
                value={profile.personalInfo.firstName}
                disabled={editingSection !== 'personal'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                title="Vnesite ime gosta"
                onChange={(e) => {
                  if (editingSection === 'personal') {
                    handleProfileUpdate({
                      personalInfo: { ...profile.personalInfo, firstName: e.target.value }
                    });
                  }
                }}
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Last Name</label>
              <input
                type="text"
                value={profile.personalInfo.lastName}
                disabled={editingSection !== 'personal'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                title="Priimek gosta"
                onChange={(e) => {
                  if (editingSection === 'personal') {
                    handleProfileUpdate({
                      personalInfo: { ...profile.personalInfo, lastName: e.target.value }
                    });
                  }
                }}
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
              <input
                type="email"
                value={profile.personalInfo.email}
                disabled={editingSection !== 'personal'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                title="Elektronski naslov gosta"
                onChange={(e) => {
                  if (editingSection === 'personal') {
                    handleProfileUpdate({
                      personalInfo: { ...profile.personalInfo, email: e.target.value }
                    });
                  }
                }}
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
              <input
                type="tel"
                value={profile.personalInfo.phone}
                disabled={editingSection !== 'personal'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                title="Telefonska številka gosta"
                onChange={(e) => {
                  if (editingSection === 'personal') {
                    handleProfileUpdate({
                      personalInfo: { ...profile.personalInfo, phone: e.target.value }
                    });
                  }
                }}
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Nationality</label>
              <input
                type="text"
                value={profile.personalInfo.nationality}
                disabled={editingSection !== 'personal'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'personal') {
                    handleProfileUpdate({
                      personalInfo: { ...profile.personalInfo, nationality: e.target.value }
                    });
                  }
                }}
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Language</label>
              <input
                type="text"
                value={profile.personalInfo.language}
                disabled={editingSection !== 'personal'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'personal') {
                    handleProfileUpdate({
                      personalInfo: { ...profile.personalInfo, language: e.target.value }
                    });
                  }
                }}
              />
            </div>
          </div>
        </div>

        {/* Guest Tags */}
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Guest Tags</h3>
          <div className="flex flex-wrap gap-2 mb-4">
            {tags.map((tag) => (
              <div
                key={tag.id}
                className="inline-flex items-center px-3 py-1 rounded-full text-sm"
                style={{ backgroundColor: tag.color + '20', color: tag.color }}
              >
                {tag.name}
                <button
                  onClick={() => handleRemoveTag(tag.id)}
                  className="ml-2 text-red-500 hover:text-red-700"
                >
                  ×
                </button>
              </div>
            ))}
          </div>
          
          <div className="flex gap-2">
            <input
              type="text"
              placeholder="Add new tag..."
              className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              onKeyPress={(e) => {
                if (e.key === 'Enter' && e.currentTarget.value.trim()) {
                  handleAddTag(e.currentTarget.value.trim(), 'preference');
                  e.currentTarget.value = '';
                }
              }}
            />
            <select
              className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              onChange={(e) => {
                const input = e.currentTarget.previousElementSibling as HTMLInputElement;
                if (input.value.trim()) {
                  handleAddTag(input.value.trim(), e.target.value);
                  input.value = '';
                }
              }}
            >
              <option value="">Category</option>
              <option value="preference">Preference</option>
              <option value="behavior">Behavior</option>
              <option value="loyalty">Loyalty</option>
              <option value="feedback">Feedback</option>
            </select>
          </div>
        </div>
      </div>
    );
  };

  const renderPreferencesTab = () => {
    if (!preferences) return null;

    return (
      <div className="space-y-6">
        {/* Room Preferences */}
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Room Preferences</h3>
            <button
              onClick={() => setEditingSection(editingSection === 'room' ? null : 'room')}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              {editingSection === 'room' ? 'Cancel' : 'Edit'}
            </button>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Preferred Room Types</label>
              <select
                multiple
                value={preferences.roomPreferences.roomType}
                disabled={editingSection !== 'room'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'room') {
                    const selectedOptions = Array.from(e.target.selectedOptions, option => option.value);
                    handlePreferencesUpdate({
                      roomPreferences: { ...preferences.roomPreferences, roomType: selectedOptions }
                    });
                  }
                }}
              >
                <option value="standard">Standard</option>
                <option value="deluxe">Deluxe</option>
                <option value="suite">Suite</option>
                <option value="presidential">Presidential</option>
              </select>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Preferred Floors</label>
              <select
                multiple
                value={preferences.roomPreferences.floor}
                disabled={editingSection !== 'room'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'room') {
                    const selectedOptions = Array.from(e.target.selectedOptions, option => option.value);
                    handlePreferencesUpdate({
                      roomPreferences: { ...preferences.roomPreferences, floor: selectedOptions }
                    });
                  }
                }}
              >
                <option value="1">1st Floor</option>
                <option value="2">2nd Floor</option>
                <option value="3">3rd Floor</option>
                <option value="4">4th Floor</option>
                <option value="5">5th Floor</option>
              </select>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Preferred View</label>
              <select
                multiple
                value={preferences.roomPreferences.view}
                disabled={editingSection !== 'room'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'room') {
                    const selectedOptions = Array.from(e.target.selectedOptions, option => option.value);
                    handlePreferencesUpdate({
                      roomPreferences: { ...preferences.roomPreferences, view: selectedOptions }
                    });
                  }
                }}
              >
                <option value="city">City View</option>
                <option value="ocean">Ocean View</option>
                <option value="garden">Garden View</option>
                <option value="mountain">Mountain View</option>
              </select>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Smoking Preference</label>
              <select
                value={preferences.roomPreferences.smoking}
                disabled={editingSection !== 'room'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'room') {
                    handlePreferencesUpdate({
                      roomPreferences: { ...preferences.roomPreferences, smoking: e.target.value as any }
                    });
                  }
                }}
              >
                <option value="prefer-smoking">Prefer Smoking</option>
                <option value="prefer-non-smoking">Prefer Non-Smoking</option>
                <option value="no-preference">No Preference</option>
              </select>
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                id="pet-friendly"
                checked={preferences.roomPreferences.petFriendly}
                disabled={editingSection !== 'room'}
                className="mr-2"
                onChange={(e) => {
                  if (editingSection === 'room') {
                    handlePreferencesUpdate({
                      roomPreferences: { ...preferences.roomPreferences, petFriendly: e.target.checked }
                    });
                  }
                }}
              />
              <label htmlFor="pet-friendly" className="text-sm font-medium text-gray-700">
                Pet Friendly
              </label>
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                id="accessible"
                checked={preferences.roomPreferences.accessibility}
                disabled={editingSection !== 'room'}
                className="mr-2"
                onChange={(e) => {
                  if (editingSection === 'room') {
                    handlePreferencesUpdate({
                      roomPreferences: { ...preferences.roomPreferences, accessibility: e.target.checked }
                    });
                  }
                }}
              />
              <label htmlFor="accessible" className="text-sm font-medium text-gray-700">
                Accessibility Required
              </label>
            </div>
          </div>
        </div>

        {/* Communication Preferences */}
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Communication Preferences</h3>
            <button
              onClick={() => setEditingSection(editingSection === 'communication' ? null : 'communication')}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              {editingSection === 'communication' ? 'Cancel' : 'Edit'}
            </button>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Preferred Language</label>
              <input
                type="text"
                value={preferences.communicationPreferences.preferredLanguage}
                disabled={editingSection !== 'communication'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'communication') {
                    handlePreferencesUpdate({
                      communicationPreferences: { ...preferences.communicationPreferences, preferredLanguage: e.target.value }
                    });
                  }
                }}
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Communication Channel</label>
              <select
                value={preferences.communicationPreferences.communicationChannel}
                disabled={editingSection !== 'communication'}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                onChange={(e) => {
                  if (editingSection === 'communication') {
                    handlePreferencesUpdate({
                      communicationPreferences: { ...preferences.communicationPreferences, communicationChannel: e.target.value as any }
                    });
                  }
                }}
              >
                <option value="email">Email</option>
                <option value="sms">SMS</option>
                <option value="phone">Phone</option>
                <option value="app">Mobile App</option>
                <option value="whatsapp">WhatsApp</option>
              </select>
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                id="marketing-consent"
                checked={preferences.communicationPreferences.marketingConsent}
                disabled={editingSection !== 'communication'}
                className="mr-2"
                onChange={(e) => {
                  if (editingSection === 'communication') {
                    handlePreferencesUpdate({
                      communicationPreferences: { ...preferences.communicationPreferences, marketingConsent: e.target.checked }
                    });
                  }
                }}
              />
              <label htmlFor="marketing-consent" className="text-sm font-medium text-gray-700">
                Marketing Communications
              </label>
            </div>
            
            <div className="flex items-center">
              <input
                type="checkbox"
                id="promotional-offers"
                checked={preferences.communicationPreferences.promotionalOffers}
                disabled={editingSection !== 'communication'}
                className="mr-2"
                onChange={(e) => {
                  if (editingSection === 'communication') {
                    handlePreferencesUpdate({
                      communicationPreferences: { ...preferences.communicationPreferences, promotionalOffers: e.target.checked }
                    });
                  }
                }}
              />
              <label htmlFor="promotional-offers" className="text-sm font-medium text-gray-700">
                Promotional Offers
              </label>
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderLoyaltyTab = () => {
    if (!loyaltyInfo) return null;

    return (
      <div className="space-y-6">
        {/* Loyalty Overview */}
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Loyalty Program</h3>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div
                className="inline-flex items-center justify-center w-16 h-16 rounded-full mb-2"
                style={{ backgroundColor: getLoyaltyTierColor(loyaltyInfo.tier) }}
              >
                <span className="text-white text-2xl font-bold">
                  {loyaltyInfo.tier.charAt(0).toUpperCase()}
                </span>
              </div>
              <h4 className="text-lg font-semibold text-gray-900 capitalize">{loyaltyInfo.tier}</h4>
              <p className="text-sm text-gray-600">Member since {format(loyaltyInfo.membershipSince, 'MMM yyyy')}</p>
            </div>
            
            <div className="text-center">
              <div className="text-3xl font-bold text-gray-900 mb-2">
                {formatLoyaltyPoints(loyaltyInfo.points)}
              </div>
              <p className="text-sm text-gray-600">Available Points</p>
              <p className="text-xs text-gray-500">Expires: {format(loyaltyInfo.pointsExpiry, 'MMM dd, yyyy')}</p>
            </div>
            
            <div className="text-center">
              <div className="text-2xl font-bold text-gray-900 mb-2">
                {loyaltyInfo.progress.pointsToNextTier}
              </div>
              <p className="text-sm text-gray-600">Points to {loyaltyInfo.progress.nextTier}</p>
              <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
                <div
                  className="bg-blue-600 h-2 rounded-full"
                  style={{ width: `${loyaltyInfo.progress.tierProgressPercentage}%` }}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Loyalty Benefits */}
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Tier Benefits</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {getLoyaltyTierBenefits(loyaltyInfo.tier).map((benefit, index) => (
              <div key={index} className="flex items-center">
                <svg className="w-5 h-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                <span className="text-sm text-gray-700">{benefit}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Points Management */}
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Points Management</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Add Points</label>
              <div className="flex gap-2">
                <input
                  type="number"
                  placeholder="Amount"
                  className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  onKeyPress={(e) => {
                    if (e.key === 'Enter') {
                      const input = e.currentTarget as HTMLInputElement;
                      if (input.value) {
                        handleAddPoints(parseInt(input.value), 'Manual adjustment');
                        input.value = '';
                      }
                    }
                  }}
                />
                <button
                  onClick={() => {
                    const input = document.querySelector('input[placeholder="Amount"]') as HTMLInputElement;
                    if (input?.value) {
                      handleAddPoints(parseInt(input.value), 'Manual adjustment');
                      input.value = '';
                    }
                  }}
                  className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
                >
                  Add
                </button>
              </div>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Quick Actions</label>
              <div className="flex gap-2">
                <button
                  onClick={() => handleAddPoints(10, 'Feedback submitted')}
                  className="px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
                >
                  +10 Feedback
                </button>
                <button
                  onClick={() => handleAddPoints(50, 'Check-in')}
                  className="px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
                >
                  +50 Check-in
                </button>
                <button
                  onClick={() => handleAddPoints(100, 'Booking')}
                  className="px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
                >
                  +100 Booking
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderRecommendationsTab = () => {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-gray-900">Personalized Recommendations</h3>
          <button
            onClick={handleGenerateRecommendations}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Generate New
          </button>
        </div>
        
        {recommendations.length === 0 ? (
          <div className="bg-white rounded-lg shadow p-6 text-center">
            <svg className="w-16 h-16 mx-auto text-gray-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.405.405M21 12h-1M4 12H3m3.343-5.657l-.405-.405M2.172 8.172l4.656 4.656M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-5 0a4 4 0 11-8 0 4 4 0 018 0z" />
            </svg>
            <p className="text-gray-600">No recommendations available</p>
            <p className="text-sm text-gray-500">Generate recommendations to see personalized suggestions</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {recommendations.map((recommendation, index) => (
              <motion.div
                key={recommendation.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="bg-white rounded-lg shadow p-6"
              >
                <div className="flex items-center justify-between mb-2">
                  <h4 className="text-lg font-semibold text-gray-900">{recommendation.title}</h4>
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                    recommendation.priority === 'high' ? 'bg-red-100 text-red-800' :
                    recommendation.priority === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                    'bg-blue-100 text-blue-800'
                  }`}>
                    {recommendation.priority}
                  </span>
                </div>
                
                <p className="text-gray-600 mb-4">{recommendation.description}</p>
                
                <div className="mb-4">
                  <div className="flex items-center justify-between text-sm text-gray-500 mb-1">
                    <span>Confidence</span>
                    <span>{Math.round(recommendation.confidence * 100)}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div
                      className="bg-blue-600 h-2 rounded-full"
                      style={{ width: `${recommendation.confidence * 100}%` }}
                    />
                  </div>
                </div>
                
                <div className="flex gap-2">
                  {recommendation.actionItems.map((action, actionIndex) => (
                    <button
                      key={actionIndex}
                      onClick={() => handleRecommendationAction(recommendation)}
                      className="flex-1 px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
                    >
                      {action.title}
                    </button>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    );
  };

  const renderHistoryTab = () => {
    return (
      <div className="space-y-6">
        {/* Stay History */}
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Stay History</h3>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Check-in</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Check-out</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Room</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nights</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Total</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {stayHistory.slice(0, 10).map((stay) => (
                  <tr key={stay.id}>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {format(stay.checkInDate, 'MMM dd, yyyy')}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {format(stay.checkOutDate, 'MMM dd, yyyy')}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {stay.roomNumber}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {stay.numberOfNights}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      ${calculateStayValue(stay).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Communication History */}
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Communication History</h3>
          <div className="space-y-3">
            {communicationHistory.slice(0, 5).map((comm) => (
              <div key={comm.id} className="border-l-4 border-blue-500 pl-4 py-2">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-sm font-medium text-gray-900">{comm.subject}</span>
                  <span className="text-xs text-gray-500">{format(comm.timestamp, 'MMM dd, yyyy HH:mm')}</span>
                </div>
                <p className="text-sm text-gray-600">{comm.content}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  const renderFeedbackTab = () => {
    return (
      <div className="space-y-6">
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Guest Feedback</h3>
          <div className="space-y-4">
            {feedback.slice(0, 10).map((item) => (
              <div key={item.id} className="border-l-4 border-yellow-500 pl-4 py-2">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-sm font-medium text-gray-900">{item.title}</span>
                  <div className="flex items-center">
                    <span className="text-sm text-gray-600 mr-2">Rating: {item.rating}/5</span>
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                      item.sentiment.label === 'positive' ? 'bg-green-100 text-green-800' :
                      item.sentiment.label === 'negative' ? 'bg-red-100 text-red-800' :
                      'bg-gray-100 text-gray-800'
                    }`}>
                      {item.sentiment.label}
                    </span>
                  </div>
                </div>
                <p className="text-sm text-gray-600 mb-2">{item.content}</p>
                {item.response && (
                  <div className="bg-gray-50 p-3 rounded">
                    <p className="text-sm text-gray-700">
                      <strong>Response:</strong> {item.response.content}
                    </p>
                    <p className="text-xs text-gray-500 mt-1">
                      Responded: {format(item.response.respondedAt, 'MMM dd, yyyy HH:mm')}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  if (isLoading && !profile) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <svg className="w-16 h-16 mx-auto text-red-500 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <h3 className="text-lg font-medium text-gray-900 mb-2">Error Loading Guest Profile</h3>
          <p className="text-gray-600 mb-4">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center">
              {profile && (
                <>
                  <h1 className="text-xl font-semibold text-gray-900 mr-4">
                    {profile.personalInfo.firstName} {profile.personalInfo.lastName}
                  </h1>
                  <span className="text-sm text-gray-500">
                    Guest ID: {profile.id}
                  </span>
                </>
              )}
            </div>
            
            <div className="flex items-center space-x-3">
              {profile && (
                <button
                  onClick={() => getInsights()}
                  className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
                >
                  Generate Insights
                </button>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex space-x-8">
            {[
              { id: 'profile', label: 'Profile' },
              { id: 'preferences', label: 'Preferences' },
              { id: 'loyalty', label: 'Loyalty' },
              { id: 'recommendations', label: 'Recommendations' },
              { id: 'history', label: 'History' },
              { id: 'feedback', label: 'Feedback' },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`py-4 px-1 border-b-2 font-medium text-sm ${
                  activeTab === tab.id
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            {activeTab === 'profile' && renderProfileTab()}
            {activeTab === 'preferences' && renderPreferencesTab()}
            {activeTab === 'loyalty' && renderLoyaltyTab()}
            {activeTab === 'recommendations' && renderRecommendationsTab()}
            {activeTab === 'history' && renderHistoryTab()}
            {activeTab === 'feedback' && renderFeedbackTab()}
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Recommendation Modal */}
      {showRecommendationModal && selectedRecommendation && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4">
            <div className="border-b border-gray-200 px-6 py-4">
              <h3 className="text-lg font-semibold text-gray-900">{selectedRecommendation.title}</h3>
            </div>
            <div className="px-6 py-4">
              <p className="text-gray-600 mb-4">{selectedRecommendation.description}</p>
              <div className="space-y-2">
                {selectedRecommendation.actionItems.map((action, index) => (
                  <button
                    key={index}
                    onClick={() => {
                      // Handle action
                      setShowRecommendationModal(false);
                      toast.success(`Action "${action.title}" initiated`);
                    }}
                    className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                  >
                    {action.title} {action.price && `($${action.price})`}
                  </button>
                ))}
              </div>
            </div>
            <div className="border-t border-gray-200 px-6 py-4">
              <div className="flex justify-end">
                <button
                  onClick={() => setShowRecommendationModal(false)}
                  className="px-4 py-2 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
