/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

export interface WorkflowNode {
  id: string
  nodeType: string
  name: string
  data: string
  timeoutMs?: number
  retryCount?: number
}

export interface WorkflowEdge {
  source: string
  target: string
  condition?: string
}

export interface WorkflowDefinition {
  id: string
  name: string
  nodes: Array<WorkflowNode>
  edges: Array<WorkflowEdge>
  metadata?: string
}

export declare enum NodeStatus {
  Pending = 0,
  Running = 1,
  Completed = 2,
  Failed = 3,
  Skipped = 4
}

export interface NodeExecutionResult {
  nodeId: string
  status: NodeStatus
  output?: string
  error?: string
  durationMs: number
  retries: number
  startedAt?: string
  completedAt?: string
}

export declare enum WorkflowStatus {
  Queued = 0,
  Running = 1,
  Completed = 2,
  Failed = 3,
  Cancelled = 4
}

export interface WorkflowExecutionResult {
  workflowId: string
  executionId: string
  status: WorkflowStatus
  nodeResults: Array<NodeExecutionResult>
  totalDurationMs: number
  startedAt: string
  completedAt?: string
  error?: string
}

export interface WorkflowProgress {
  executionId: string
  completedNodes: number
  totalNodes: number
  currentNode?: string
  status: WorkflowStatus
  percentComplete: number
}

/**
 * Execute a workflow with all nodes and edges
 *
 * # Arguments
 * * `workflow` - Workflow definition with nodes and edges
 *
 * # Returns
 * WorkflowExecutionResult with status and node results
 *
 * # Example
 * ```
 * let result = execute_workflow(workflow_def).await?;
 * println!("Status: {:?}", result.status);
 * ```
 */
export function executeWorkflow(workflow: WorkflowDefinition): Promise<WorkflowExecutionResult>

/**
 * Validate workflow structure without executing
 */
export function validateWorkflow(workflow: WorkflowDefinition): void

/**
 * Get execution plan (topological order) without running
 */
export function getExecutionPlan(workflow: WorkflowDefinition): Array<string>

/**
 * Create a progress tracker for real-time monitoring
 */
export function createProgressTracker(executionId: string, totalNodes: number): WorkflowProgress

/**
 * Helper class for workflow execution
 */
export class WorkflowExecutor {
  constructor(options?: { timeout?: number; retries?: number })
  
  /**
   * Execute a workflow
   */
  execute(workflow: WorkflowDefinition): Promise<WorkflowExecutionResult>
  
  /**
   * Validate a workflow without executing
   */
  validate(workflow: WorkflowDefinition): boolean
  
  /**
   * Get execution plan (topological order)
   */
  getPlan(workflow: WorkflowDefinition): Array<string>
}
