/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Individual price adjustment from a rule */
export interface Adjustment {
  rule: string
  amount: number
  percent?: number
}

/** Batch input for multiple price calculations */
export interface BatchPricingInput {
  requests: Array<BatchPricingRequest>
}

export interface BatchPricingRequest {
  id: string
  baseRate: number
  checkIn: string
  checkOut: string
  options?: PricingOptions
}

export interface BatchPricingResponse {
  id: string
  result: PricingResult
}

/**
 * Calculate price for a booking with all applicable rules and adjustments
 *
 * # Arguments
 * * `base_rate` - Base nightly rate in EUR
 * * `check_in` - Check-in date (YYYY-MM-DD format)
 * * `check_out` - Check-out date (YYYY-MM-DD format)
 * * `options` - Optional pricing configuration (season rates, competitor pricing)
 *
 * # Returns
 * PricingResult with base total, adjustments, and final price
 *
 * # Example
 * ```
 * let result = calculate_price(100.0, "2026-07-01", "2026-07-08", None);
 * assert_eq!(result.nights, 7);
 * ```
 */
export declare function calculatePrice(baseRate: number, checkIn: string, checkOut: string, options?: PricingOptions | undefined | null): PricingResult

/** Calculate prices for multiple requests in a single batch */
export declare function calculatePriceBatch(input: BatchPricingInput): Array<BatchPricingResponse>

/** Detailed price breakdown for transparency */
export interface PriceBreakdown {
  ratePerNight: number
  subtotal: number
  totalDiscounts: number
  totalPremiums: number
}

/** Pricing calculation options */
export interface PricingOptions {
  competitorAvg?: number
  seasonRates?: SeasonRates
}

/** Result of pricing calculation */
export interface PricingResult {
  baseTotal: number
  adjustments: Array<Adjustment>
  finalPrice: number
  nights: number
  breakdown?: PriceBreakdown
}

/** Seasonal pricing range with start/end dates and rate */
export interface SeasonRange {
  from: string
  to: string
  rate: number
}

/** Seasonal rates configuration (high/mid/low seasons) */
export interface SeasonRates {
  high?: Array<SeasonRange>
  mid?: Array<SeasonRange>
  low?: Array<SeasonRange>
}
