#!/usr/bin/env node

/**
 * Prisma Schema Modularization Script
 * Splits monolithic schema.prisma into domain modules
 */

const fs = require('fs');
const path = require('path');

const SCHEMA_PATH = path.join(__dirname, '..', 'prisma', 'schema.prisma');
const MODULES_DIR = path.join(__dirname, '..', 'prisma', 'modules');

// Domain mapping - kateri modeli spadajo v katero domeno
const DOMAIN_MAPPING = {
  'user.prisma': [
    'User', 'UserProfile', 'UserApiKey', 'UserTemplate', 'UsageAlert',
    'Onboarding', 'Branding', 'CustomRole', 'UserRole'
  ],
  'property.prisma': [
    'Property', 'Room', 'Amenity', 'BlockedDate', 'Competitor',
    'PropertyPolicy', 'PropertyAmenity', 'PropertyPhoto', 'PropertyFeature',
    'AjpesConnection', 'PmsConnection', 'PerformanceMetric'
  ],
  'reservation.prisma': [
    'Reservation', 'ReservationLog', 'ReservationPayment',
    'ReservationCommunication', 'ReservationTimeline', 'ReservationChannel'
  ],
  'guest.prisma': [
    'Guest', 'GuestProfile', 'GuestCommunication', 'GuestPreference',
    'GuestRequest', 'GuestFeedback', 'GuestDocument', 'Inquiry'
  ],
  'payment.prisma': [
    'Payment', 'PaymentMethod', 'PaymentLog', 'Refund', 'Invoice',
    'InvoiceItem', 'TaxRate', 'RevenueSplit', 'Subscription',
    'Billing', 'Payout', 'ChannelRate', 'DynamicPricing'
  ],
  'agent.prisma': [
    'Agent', 'AgentRun', 'AgentRunView', 'AgentRunStep', 'AgentLog',
    'AgentTemplate', 'AgentConfig', 'AgentMetrics', 'AgentQuota'
  ],
  'workflow.prisma': [
    'Workflow', 'WorkflowExecution', 'WorkflowVersion', 'WorkflowCheckpoint',
    'WorkflowEvent', 'WorkflowSnapshot', 'WorkflowNode', 'WorkflowEdge',
    'WorkflowTemplate', 'WorkflowTrigger', 'WorkflowAction'
  ],
  'analytics.prisma': [
    'AnalyticsRunStats', 'AnalyticsDailyStats', 'AnalyticsEvent',
    'AnalyticsMetric', 'AnalyticsReport', 'Dashboard', 'DashboardWidget'
  ],
  'content.prisma': [
    'Content', 'ContentVersion', 'ContentTemplate', 'ContentLog',
    'BlogPost', 'LandingPage', 'PageDesign', 'ContentCalendar',
    'ContentApproval', 'ContentMetrics', 'SeoMetric', 'TranslationJob'
  ],
  'communication.prisma': [
    'Message', 'MessageGroup', 'MessageGroupMember', 'MessageThread',
    'Notification', 'NotificationPreference', 'EmailTemplate',
    'SmsTemplate', 'CommunicationLog', 'ChatEscalation', 'ConversationThread'
  ],
  'team.prisma': [
    'Team', 'TeamMember', 'Workspace', 'Invite', 'CampaignBoard',
    'Task', 'TaskCollaboration', 'StaffAssignment', 'StaffSchedule',
    'Employee', 'HousekeepingTask', 'HousekeepingSchedule'
  ],
  'tourism.prisma': [
    'Owner', 'Review', 'ReviewRequest', 'Itinerary', 'Faq',
    'FaqResponseLog', 'ChannelManager', 'ChannelMapping',
    'ChannelLog', 'SustainabilityMetric', 'EcoPractice',
    'EcoCertification', 'PhotoAnalysis', 'DailyRate', 'OccupancyRate'
  ],
  'system.prisma': [
    'Account', 'Session', 'VerificationToken', 'PasswordResetToken',
    'AuditLog', 'EventLog', 'TemplateUsage', 'AlertEvent', 'AlertRule',
    'SmartAlertLog', 'ContactSubmission', 'SystemLog', 'ErrorLog',
    'FeatureFlag', 'RateLimit', 'ApiKey'
  ],
  'integration.prisma': [
    'Integration', 'IntegrationLog', 'IntegrationConfig',
    'Webhook', 'WebhookLog', 'OAuthConnection', 'ApiConnection'
  ]
};

function readSchema() {
  return fs.readFileSync(SCHEMA_PATH, 'utf8');
}

function extractModels(schema) {
  const models = {};
  const modelRegex = /model\s+(\w+)\s*\{[\s\S]*?\n\}/g;
  let match;
  
  while ((match = modelRegex.exec(schema)) !== null) {
    const modelName = match[1];
    const modelContent = match[0];
    models[modelName] = modelContent;
  }
  
  return models;
}

function extractEnums(schema) {
  const enums = {};
  const enumRegex = /enum\s+(\w+)\s*\{[\s\S]*?\n\}/g;
  let match;
  
  while ((match = enumRegex.exec(schema)) !== null) {
    const enumName = match[1];
    const enumContent = match[0];
    enums[enumName] = enumContent;
  }
  
  return enums;
}

function extractGeneratorDatasource(schema) {
  const generatorMatch = schema.match(/generator\s+client\s*\{[\s\S]*?\n\}/);
  const datasourceMatch = schema.match(/datasource\s+db\s*\{[\s\S]*?\n\}/);
  
  return {
    generator: generatorMatch ? generatorMatch[0] : '',
    datasource: datasourceMatch ? datasourceMatch[0] : ''
  };
}

function createModuleFile(domain, models, enums) {
  let content = `// ${domain} - Prisma Models\n`;
  content += `// Auto-generated by scripts/modularize-prisma.js\n\n`;
  
  // Add enums first
  Object.values(enums).forEach(enumContent => {
    content += `${enumContent}\n\n`;
  });
  
  // Add models
  Object.values(models).forEach(modelContent => {
    content += `${modelContent}\n\n`;
  });
  
  return content.trim();
}

function createMainSchema(domains) {
  const { generator, datasource } = extractGeneratorDatasource(readSchema());
  
  let content = `${generator}\n\n${datasource}\n\n`;
  content += `// ============================================================================\n`;
  content += `// MAIN PRISMA SCHEMA - Auto-generated\n`;
  content += `// ============================================================================\n`;
  content += `//\n`;
  content += `// This file imports all domain modules.\n`;
  content += `// DO NOT edit this file directly - edit domain files in modules/ instead.\n`;
  content += `//\n`;
  content += `// Domains:\n`;
  
  domains.forEach((domain, i) => {
    content += `//   ${i + 1}. ${domain}\n`;
  });
  
  content += `//\n`;
  content += `// ============================================================================\n\n`;
  
  // Note: Prisma doesn't support imports yet, so we'll concatenate
  // In the future, this would use import statements
  content += `// NOTE: Prisma does not currently support imports.\n`;
  content += `// All models are concatenated in this file from modules/.\n`;
  content += `// Run \`npm run prisma:modularize\` to regenerate.\n\n`;
  
  return content;
}

function main() {
  console.log('🔧 Prisma Schema Modularization\n');
  
  // Create modules directory
  if (!fs.existsSync(MODULES_DIR)) {
    fs.mkdirSync(MODULES_DIR, { recursive: true });
    console.log(`✓ Created ${path.relative(process.cwd(), MODULES_DIR)}/`);
  }
  
  // Read schema
  const schema = readSchema();
  console.log('✓ Read schema.prisma');
  
  // Extract all models and enums
  const allModels = extractModels(schema);
  const allEnums = extractEnums(schema);
  const { generator, datasource } = extractGeneratorDatasource(schema);
  
  console.log(`✓ Found ${Object.keys(allModels).length} models`);
  console.log(`✓ Found ${Object.keys(allEnums).length} enums`);
  
  // Group models by domain
  const domainModels = {};
  const unmappedModels = [];
  
  Object.entries(DOMAIN_MAPPING).forEach(([domain, modelNames]) => {
    domainModels[domain] = {};
    
    modelNames.forEach(modelName => {
      if (allModels[modelName]) {
        domainModels[domain][modelName] = allModels[modelName];
        delete allModels[modelName];
      }
    });
  });
  
  // Check for unmapped models
  if (Object.keys(allModels).length > 0) {
    console.log('\n⚠️  Unmapped models (will be added to system.prisma):');
    Object.keys(allModels).forEach(modelName => {
      console.log(`   - ${modelName}`);
      if (!domainModels['system.prisma']) {
        domainModels['system.prisma'] = {};
      }
      domainModels['system.prisma'][modelName] = allModels[modelName];
    });
  }
  
  // Write domain modules
  console.log('\n📦 Creating domain modules:');
  Object.entries(domainModels).forEach(([domain, models]) => {
    if (Object.keys(models).length === 0) return;
    
    const modulePath = path.join(MODULES_DIR, domain);
    const content = createModuleFile(domain, models, allEnums);
    fs.writeFileSync(modulePath, content);
    
    console.log(`  ✓ ${domain} (${Object.keys(models).length} models)`);
  });
  
  // Write main schema (concatenated for now)
  const mainSchemaPath = path.join(__dirname, '..', 'prisma', 'schema.prisma');
  const mainSchemaContent = createMainSchema(Object.keys(DOMAIN_MAPPING));
  
  // For now, keep original schema as backup and create new one
  const backupPath = path.join(__dirname, '..', 'prisma', 'schema.original.prisma');
  fs.copyFileSync(mainSchemaPath, backupPath);
  console.log(`\n✓ Created backup: schema.original.prisma`);
  
  // Concatenate all modules into main schema
  let fullSchema = mainSchemaContent;
  Object.entries(domainModels).forEach(([domain, models]) => {
    fullSchema += `\n\n// ============================================================================\n`;
    fullSchema += `// ${domain.toUpperCase()}\n`;
    fullSchema += `// ============================================================================\n\n`;
    
    const modulePath = path.join(MODULES_DIR, domain);
    const moduleContent = fs.readFileSync(modulePath, 'utf8');
    fullSchema += moduleContent + '\n';
  });
  
  fs.writeFileSync(mainSchemaPath, fullSchema);
  console.log(`✓ Updated schema.prisma (concatenated from modules)`);
  
  console.log('\n✅ Modularization complete!\n');
  console.log('Next steps:');
  console.log('  1. Review generated modules in prisma/modules/');
  console.log('  2. Run: npm run db:generate');
  console.log('  3. Run: npm run db:migrate (if needed)\n');
}

main();
